import os
import glob
import json
import sys
import re

# Add project root to sys.path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from core.gemini_client import generate_with_rotation

def phoneticize_script(script_text: str):
    """
    Scans a raw script text for complex proper nouns, locations, or names,
    queries the LLM for their phonetic pronunciations, and caches them globally.
    """
    map_path = os.path.join("config", "phonetic_map.json")
    
    # Load existing map
    if os.path.exists(map_path):
        with open(map_path, "r", encoding="utf-8") as f:
            phonetic_map = json.load(f)
    else:
        phonetic_map = {}

    # Extract clean words that are already mapped (strip regex \b)
    mapped_words = set()
    for key in phonetic_map.keys():
        clean_key = re.sub(r'\\b', '', key).replace('\\.', '.')
        mapped_words.add(clean_key.lower())

    prompt = f"""
You are an expert pronunciation assistant for the Kokoro Text-to-Speech engine.
Read the following script. The TTS engine natively handles 99% of English words perfectly.
Your ONLY job is to identify extremely rare foreign proper nouns, complex Indian/Asian names, or obscure abbreviations that a native English speaker would struggle to read.

CRITICAL RULES:
1. ONLY extract words if they are genuinely foreign or obscure names (e.g., "Sooryavanshi", "Poughkeepsie", "BCCI").
2. DO NOT extract normal English words, compound words, or common names (e.g., "detective", "multimillion", "defendants", "Michael").
3. NEVER USE HYPHENS in the pronunciation. Kokoro reads hyphens out loud, ruining the audio.
4. If you must provide a pronunciation, write it as SPACE-SEPARATED REAL ENGLISH WORDS (e.g., "Sooryavanshi" -> "soory ah van shee", "BCCI" -> "B C C I").
5. If there are no highly complex foreign names in the script, return an EMPTY JSON object {{}}.

Script text:
\"\"\"{script_text}\"\"\"

Return ONLY a valid JSON object.
"""

    print("[Auto-Phoneticize] Scanning script for unmapped complex words...")
    try:
        raw_resp = generate_with_rotation(prompt, response_format={"type": "json_object"}, temperature=0.1)
        
        # Clean markdown if returned
        if "```json" in raw_resp:
            raw_resp = raw_resp.split("```json")[1].split("```")[0]
        elif "```" in raw_resp:
            raw_resp = raw_resp.split("```")[1].split("```")[0]

            
        new_mappings = json.loads(raw_resp.strip())
        
        if not new_mappings:
            print("[Auto-Phoneticize] No new complex words found in script.")
            return

        # Inject new mappings into the global phonetic map (if not already mapped)
        added_count = 0
        for word, pronunciation in new_mappings.items():
            if word.lower() not in mapped_words:
                # Sanitize: replace any hyphens generated by the LLM with spaces
                sanitized_pronunciation = pronunciation.replace("-", " ")
                regex_key = f"\\b{word}\\b"
                phonetic_map[regex_key] = sanitized_pronunciation
                added_count += 1
            
        if added_count > 0:
            # Save updated map
            os.makedirs("config", exist_ok=True)
            with open(map_path, "w", encoding="utf-8") as f:
                json.dump(phonetic_map, f, indent=2, ensure_ascii=False)
            print(f"[Auto-Phoneticize] Successfully cached {added_count} new phonetic spellings: {list(new_mappings.keys())}")
        else:
            print("[Auto-Phoneticize] Words were found by LLM but are already cached.")

    except Exception as e:
        print(f"[Auto-Phoneticize] Failed to generate or parse LLM response: {e}")

def main():
    map_path = os.path.join("config", "phonetic_map.json")
    
    # Scan all channels for new vocabulary
    new_words = set()
    channel_files = glob.glob(os.path.join("channels", "*.json"))
    
    for cfile in channel_files:
        try:
            with open(cfile, "r", encoding="utf-8") as f:
                data = json.load(f)
                vocab = data.get("VOCABULARY", [])
                for word in vocab:
                    new_words.add(word)
        except Exception as e:
            print(f"Failed to read {cfile}: {e}")

    if not new_words:
        print("[Auto-Phoneticize] No vocabulary words found in channels.")
        return

    # Just run the main function logic on the giant list of words
    synthetic_script = " ".join(list(new_words))
    phoneticize_script(synthetic_script)

if __name__ == "__main__":
    main()
